#!/bin/bash
#Skrypt inpath sprawdza czy dany program jest sam w sobie poprawny
#oraz czy jest zapisany w zmiennej PATH

in_path()
{
	#Funckja starajaca sie odnalezc program na podst. nazwy i zmiennej PATH
	#Zwraca 0 jesli program istnieje i jest wykonywalny, w innym przypadku zwraca 1
	
	cmd=$1	ourpath=$2	result=1
	oldIFS=$IFS	IFS=":"

	for directory in "$ourpath"
	do 
	 if [ -x $directory/$cmd ] ; then
		result=0 #jesli dojdziemy tutaj oznacza to ze program #cmd jest w katalogu $directory
	 fi
	done

	IFS=$oldIFS
	return $result
}

checkForCmdInPath()
{
 var=$1
 
 if [ "$var" != "" ] ; then
   if [ "${var:0:1}" = "/" ] ; then
     if [ ! -x $var ] ; then
	return 1
     fi
   elif ! in_path $var "$PATH" ; then
	return 2
   fi
 fi
} 	

if [ $# -ne 1 ] ; then
  echo "Użycie: $0 polecenie" >$2 ; exit 1
fi

checkForCmdInPath "$1"
case $? in
 0 ) echo "$1 znajduje sie w katalogach zmiennej PATH."	;;
 1 ) echo "$1 nie istnieje i nie jest to plik wykonywalny" ;;
 2 ) echo "$1 nie znajduje sie w katalogach zmiennej PATH" ;;
esac 

exit 0
 
